version: '3.8'

services:
  whatsapp-agent:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DASHBOARD_PORT=4000
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - HOME=/home/nodejs
      # - OPENAI_API_KEY=your_openai_api_key
      # - OPENAI_MODEL=gpt-4o-mini
      # - SYSTEM_PROMPT=You are a helpful WhatsApp assistant. Keep replies brief and friendly.
    command: ["npm", "run", "start:web"]
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./uploads:/app/uploads
    user: "1001:1001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add PostgreSQL for production
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: whatsapp_agent
  #     POSTGRES_USER: whatsapp_user
  #     POSTGRES_PASSWORD: your_password_here
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
